source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.2'

target 'accepton_Example', :exclusive => true do
  pod "accepton", :path => "../"
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']

end

target 'accepton_Tests', :exclusive => true do
  pod "accepton", :path => "../"

 pod 'Quick', '~> 0.7.0'
 pod 'Nimble', '~> 2.0.0'
end
